boss_timers = [
    {"name": "คูทุม", "day_of_week": "Monday", "time": "00:30"},
    {"name": "นูเวอร์", "day_of_week": "Tuesday", "time": "00:30"},
    {"name": "คจาคาร์ & โอฟิน", "day_of_week": "Wednesday", "time": "00:30"},
    {"name": "คูทุม", "day_of_week": "Thursday", "time": "00:30"},
    {"name": "นูเวอร์", "day_of_week": "Friday", "time": "00:30"},
    {"name": "คารานด้า", "day_of_week": "Saturday", "time": "00:30"},
    {"name": "คจาคาร์", "day_of_week": "Sunday", "time": "00:30"},
    {"name": "คจาคาร์ & นูเวอร์", "day_of_week": "Monday", "time": "10:00"},
    {"name": "คูทุม & คารานด้า", "day_of_week": "Tuesday", "time": "10:00"},
    {"name": "คูทุม & นูเวอร์", "day_of_week": "Wednesday", "time": "10:00"},
    {"name": "คารานด้า & คจาคาร์", "day_of_week": "Thursday", "time": "10:00"},
    {"name": "คูทุม & คจาคาร์", "day_of_week": "Friday", "time": "10:00"},
    {"name": "คูทุม & คจาคาร์", "day_of_week": "Saturday", "time": "10:00"},
    {"name": "คจาคาร์ & คารานด้า", "day_of_week": "Sunday", "time": "10:00"},
    {"name": "คูทุม & นูเวอร์", "day_of_week": "Monday", "time": "14:00"},
    {"name": "คูทุม & คจาคาร์", "day_of_week": "Tuesday", "time": "14:00"},
    {"name": "คารานด้า & คจาคาร์", "day_of_week": "Wednesday", "time": "14:00"},
    {"name": "คูทุม & นูเวอร์", "day_of_week": "Thursday", "time": "14:00"},
    {"name": "คารานด้า & คจาคาร์", "day_of_week": "Friday", "time": "14:00"},
    {"name": "คารานด้า & นูเวอร์", "day_of_week": "Saturday", "time": "14:00"},
    {"name": "คูทุม & คารานด้า", "day_of_week": "Sunday", "time": "14:00"},
    {"name": "กามอธ", "day_of_week": "Saturday", "time": "15:00"},
    {"name": "เบลล์", "day_of_week": "Sunday", "time": "15:00"},
    {"name": "คจาคาร์ & คารานด้า", "day_of_week": "Monday", "time": "19:00"},
    {"name": "มูลัคคา & กวินท์", "day_of_week": "Tuesday", "time": "19:00"},
    {"name": "คูทุม & นูเวอร์", "day_of_week": "Wednesday", "time": "19:00"},
    {"name": "นูเวอร์ & คารานด้า", "day_of_week": "Thursday", "time": "19:00"},
    {"name": "คูทุม & นูเวอร์", "day_of_week": "Friday", "time": "19:00"},
    {"name": "มูลัคคา & กวินท์", "day_of_week": "Saturday", "time": "19:00"},
    {"name": "คจาคาร์ & คารานด้า", "day_of_week": "Sunday", "time": "19:00"},
    {"name": "โอฟิน", "day_of_week": "Monday", "time": "23:00"},
    {"name": "กามอธ", "day_of_week": "Tuesday", "time": "23:00"},
    {"name": "เบลล์", "day_of_week": "Wednesday", "time": "23:00"},
    {"name": "กามอธ", "day_of_week": "Thursday", "time": "23:00"},
    {"name": "โอฟิน", "day_of_week": "Friday", "time": "23:00"},
    {"name": "คูทุม & นูเวอร์", "day_of_week": "Sunday", "time": "23:00"},
    {"name": "test", "day_of_week": "Sunday", "time": "6:01"},
    ]
    
weekday_dict = {
    'Monday': 0,
    'Tuesday': 1,
    'Wednesday': 2,
    'Thursday': 3,
    'Friday': 4,
    'Saturday': 5,
    'Sunday': 6
}
